server:
  port: 8888

spring:
  devtools:
    restart:
      enabled: true #热加载生效
      additional-paths: src/main/java # 额外新增的热加载目录
      exclude: # 热加载排除目录
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123qwe!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

jasypt:
  encryptor:
    password: 123456


