spring:
  profiles:
    active: prod

# 实际最常用的是用命令行启动jar包  java -jar xxxxx.jar --spring.profiles.active=prod

# 也可以在idea命令行参数中加上命令
  # VM options 设置参数-Dspring.profiles.active=prod
  # Program arguments设置 --spring.profiles.active=prod

# 环境优先级是 外部 > 内部   特殊 > 范式